# Generated by Django 3.2 on 2021-04-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Bâtiment',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhesion_id', models.IntegerField(verbose_name='ID sur Adhésion')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email adhésion')),
                ('rfid_uid', models.CharField(max_length=255, verbose_name='ID du badge RFID')),
                ('washing_tokens_count', models.IntegerField(default=0, verbose_name='Nombre de jetons')),
            ],
            options={
                'verbose_name': 'Habitant des résidences',
                'verbose_name_plural': 'Habitants des résidences',
            },
        ),
        migrations.CreateModel(
            name='WashingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('duration', models.DurationField(verbose_name='Durée')),
            ],
            options={
                'verbose_name': 'Programe',
            },
        ),
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('short_name', models.CharField(max_length=10, verbose_name='Nom court')),
                ('number', models.IntegerField(verbose_name='Numéro')),
                ('machine_type', models.CharField(choices=[('washing_machine', 'Machine à laver'), ('dryer', 'Sèche-linge')], max_length=64, verbose_name='Type de machine')),
                ('cost', models.IntegerField(default=1, verbose_name="Coût d'une utilisation")),
                ('enabled', models.BooleanField(default=False, verbose_name='Activée (non HS)')),
                ('timer', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date+heure de fin de cycle')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.building', verbose_name='Bâtiment')),
                ('programs', models.ManyToManyField(related_name='machine', to='api.WashingProgram')),
            ],
            options={
                'verbose_name': 'Machine à laver',
                'verbose_name_plural': 'Machines à laver',
            },
        ),
    ]
