# Generated by Django 3.2 on 2021-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='rfid_uid',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID du badge RFID'),
        ),
    ]
